paths:
  label_file: "./data_SDS_score.csv"
  spectrogram_root: "./spect"

model:
  input_size: 512
  hidden_size: 128
  num_layers: 2
  num_classes: 3

training:
  batch_size: 16
  learning_rate: 0.001
  step_size: 5
  gamma: 0.5
  num_epochs: 10
